### ISSUE TITLE
[react-jss] classNamePrefix doesn't work with SSR

### ISSUE THREAD

**Issue by chrisands** [cssinjs/jss#1119]
__Expected behavior:__
ClassNames generated on server and client identical.

__Describe the bug:__
ClassNames generated on a client should be with a prefix

__Codesandbox link:__ 
https://codesandbox.io/s/jss-testdashboard-esofu

__Versions (please complete the following information):__
 - jss: 10-alpha.17
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: macOS mojave

**Comment by HenriBeck** [comment]
Seems to me that react is somehow reusing the context between renders.

**Comment by kof** [comment]
fixed https://github.com/cssinjs/jss/pull/1147

**Comment by kof** [comment]
10.0.0-alpha.22 released

**Comment by chrisands** [comment]
@kof It seems that there still an issue. 
<details>
  <summary>Screenshot</summary>
  <img src="https://i.imgur.com/KxClFy8.png" />
</details>


On server and on client class name generates differently if I go with production build. And not all names differ. For example, `App-app-0-2-1` is the same on server and client.

**Comment by HenriBeck** [comment]
But that looks to me as if react is not properly being bundled here.

The ids at the end are the same, but the prefix is not. In the styles it is `m` which looks to me is the minified name of a component.

**Comment by chrisands** [comment]
What you mean by saying not properly bundled? 

Yes, it is minified name of the component.

**Comment by kof** [comment]
which option is it? Can we do anything to make user realize this easier?

**Comment by chrisands** [comment]
As I understand, I use non-minified version of React on server `import { renderToString } from 'react-dom/server'` so on a server I get one output and on a client, I got another output because it is minified by webpack.

 I think it is possible to check `NODE_ENV` and import minified version of `react-dom/server`, but I was getting an error when I tried to do it (probably did something wrong).
`Error: Invariant failed: You should not use <withRouter(JssContextSubscriber) /> outside a <Router>`



Problem is that `getDisplayName` gets a minified version of the component name (I think it is a random letter). 
It is possible to disable name mangling via optimization options.

```js
optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        terserOptions: {
          mangle: false,
        },
      }),
    ],
  },
```

I think with `UglifyJs` there is workaround too.



We could change add this information to docs users could manually check if it's get minified or change`getDisplayName` behavior and disable it in production and also add a check for same `NODE_ENV` on server and client. AFAIK `getDisplayName` should be deprecated as HOC itself.
